### ISSUE TITLE
Custom check animation speed

### ISSUE THREAD

**Issue by nkemcels** [stanleyxu2005/react-checkmark#8]
Hello Stanley.
First, thanks for this wonderful library. It's been of so much use to me.
I would love to know how I can customize the animation duration for the check. Thanks.

**Comment by stanleyxu2005** [comment]
Sound's like a good idea ;-)

**Comment by stanleyxu2005** [comment]
There are 3 classes with animation controls. Each class has different duration settings. 

```css
.checkmark {
  animation: fill 0.4s ease-in-out 0.4s forwards, scale 0.3s ease-in-out 0.9s both;
}

.checkmark__circle {
  animation: stroke 0.6s cubic-bezier(0.65, 0, 0.45, 1) forwards;
}

.checkmark__check {
  animation: stroke 0.3s cubic-bezier(0.65, 0, 0.45, 1) 0.8s forwards;
}

@keyframes stroke {
  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes scale {
  0%,
  100% {
    transform: none;
  }
  50% {
    transform: scale3d(1.1, 1.1, 1);
  }
}

@keyframes fill {
  100% {
    box-shadow: inset 0 0 0 100vh var(--checkmark-fill-color);
  }
}
```

As you can see, there are diverse animation controls with different timing. What's your recommended animation speed, if you would like to tweak? I'm open for suggestions @nkemcels 

**Possible solution 1:** 
You can override these 3 classes with fill with your preferred timing.

**Possible solution 2:** 
Based on feedback, I can provide some preset to pick.
